import { NextRequest, NextResponse } from "next/server";
import { authenticate, createSession, ensureSeedUser, getUserFromSession, registerUser, sessionCookieName } from "@/lib/auth";
import { DEMO_META, accessibility, acknowledgeAlert, activeAlerts, aiRisk, copilotQuery, createDelivery, createIncident, currentScores, dashboardSummary, listDeliveries, listIncidents, liveVehicles, optimiseRoute, recommendHubs, resetSimulation, simulateIncident, updateDelivery } from "@/lib/demo-backend";
import { CORRIDORS, DISTRICTS } from "@/lib/ner-data";

const json = (data: unknown, status = 200) => NextResponse.json(data, { status, headers: { "Cache-Control": "no-store" } });
async function body(request: NextRequest) { try { return await request.json() as Record<string, unknown>; } catch { return {}; } }
const operationalRoles = new Set(["ADMIN", "LOGISTICS_OPERATOR", "EMERGENCY_OFFICER"]);
function systemHealth() {
  const now = new Date().toISOString();
  return {
    ...DEMO_META,
    checkedAt: now,
    services: [
      { name: "Next.js API backend", status: "RUNNING", httpStatus: 200, lastSuccessfulCheck: now, detail: "This response was generated by the active API process." },
      { name: "Browser frontend", status: "NOT_SERVER_PROBED", httpStatus: null, lastSuccessfulCheck: null, detail: "Browser rendering cannot be verified from the backend health endpoint." },
      { name: "Database", status: "NOT_CONFIGURED", httpStatus: null, lastSuccessfulCheck: null, detail: "The current demo repository uses process memory; DATABASE_URL is not connected." },
      { name: "AI service", status: "NOT_CONFIGURED", httpStatus: null, lastSuccessfulCheck: null, detail: "Risk calculations run in the demo backend; no external ML service is configured." },
      { name: "Routing service", status: "SIMULATION", httpStatus: null, lastSuccessfulCheck: now, detail: "Seeded corridor graph is in use; OSRM is not called." },
      { name: "Incident feed", status: "NOT_CONFIGURED", httpStatus: null, lastSuccessfulCheck: null, detail: "There is no configured live official incident-feed adapter." },
      { name: "GPS integration", status: "SIMULATION", httpStatus: null, lastSuccessfulCheck: now, detail: "Vehicle locations are demo positions, not live GPS." },
    ],
  };
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const path = (await params).path.join("/");
  if (path === "auth/me") {
    await ensureSeedUser();
    const user = getUserFromSession(request.cookies.get(sessionCookieName())?.value);
    return user ? json({ user: { id: user.id, email: user.email, name: user.name, role: user.role } }) : json({ detail: "Authentication required" }, 401);
  }
  const user = getUserFromSession(request.cookies.get(sessionCookieName())?.value);
  if (!path.startsWith("auth/") && !user) {
    return json({ detail: "Authentication required" }, 401);
  }
  if (path === "health" || path === "system/health") {
    if (user?.role !== "ADMIN") return json({ detail: "Administrator permission required" }, 403);
    return json(systemHealth());
  }
  if (path === "dashboard/summary") return json(dashboardSummary());
  if (path === "vehicles" || path === "vehicles/live") return json({ ...DEMO_META, mode: "SIMULATION", vehicles: liveVehicles() });
  if (path === "incidents") return json({ ...DEMO_META, incidents: listIncidents() });
  if (path === "deliveries") return json({ ...DEMO_META, mode: "SIMULATION", deliveries: listDeliveries() });
  if (path.startsWith("deliveries/")) {
    const delivery = listDeliveries().find((item) => item.id === path.split("/")[1]);
    return delivery ? json({ ...DEMO_META, mode: "SIMULATION", delivery }) : json({ detail: "Delivery not found" }, 404);
  }
  if (path === "alerts") return json({ ...DEMO_META, alerts: activeAlerts() });
  if (path === "weather") return json({ ...DEMO_META, weather_mode: "DEMO WEATHER DATA", corridors: currentScores().scores.map((score) => ({ corridor_id: score.corridorId, rainfall_mm: score.rainfallMm, warning: score.level })) });
  if (path === "accessibility/districts") return json({ ...DEMO_META, districts: accessibility() });
  if (path === "hubs") return json(recommendHubs({ destination: "kamrup" }));
  if (path.startsWith("routes/")) return json({ ...DEMO_META, id: path.split("/")[1], message: "Route persistence is not enabled in demo mode; use POST /api/routes/optimize." });
  if (path === "locations") return json({ ...DEMO_META, districts: DISTRICTS, corridors: CORRIDORS });
  return json({ detail: `Unknown GET endpoint /api/${path}` }, 404);
}

export async function POST(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const path = (await params).path.join("/");
  const input = await body(request);
  try {
    if (path === "auth/login" || path === "auth/register") {
      const user = path === "auth/login"
        ? await authenticate({ email: String(input.email ?? ""), password: String(input.password ?? "") })
        : await registerUser({ email: String(input.email ?? ""), password: String(input.password ?? ""), name: String(input.name ?? "") });
      const response = json({ user });
      response.cookies.set(sessionCookieName(), createSession(user.id), { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 8 * 60 * 60, path: "/" });
      return response;
    }
    const user = getUserFromSession(request.cookies.get(sessionCookieName())?.value);
    if (!user) return json({ detail: "Authentication required" }, 401);
    if (path === "routes/optimize") return json(optimiseRoute(input));
    if (path === "routes/recalculate") { const result = optimiseRoute(input); return json({ ...DEMO_META, current_route: input.current_route ?? null, updated_route: result.options[0], reason_for_change: input.reason ?? "Updated rainfall, incident, and congestion conditions", old_eta_hours: input.old_eta_hours ?? null, new_eta_hours: result.options[0]?.estimated_travel_hours, new_risk_score: result.options[0]?.risk_score }); }
    if (path === "ai/flood-risk") return json(aiRisk(input, "flood"));
    if (path === "ai/landslide-risk") return json(aiRisk(input, "landslide"));
    if (path === "ai/route-risk") return json({ ...DEMO_META, scores: currentScores().scores });
    if (path === "incidents") return json({ ...DEMO_META, incident: createIncident(input) }, 201);
    if (path === "deliveries") {
      if (!operationalRoles.has(user.role)) return json({ detail: "Operational role required" }, 403);
      return json({ ...DEMO_META, mode: "SIMULATION", delivery: createDelivery(input) }, 201);
    }
    if (path === "simulation/incidents") {
      if (user.role !== "ADMIN") return json({ detail: "Administrator permission required" }, 403);
      return json({ ...DEMO_META, ...simulateIncident(input) }, 201);
    }
    if (path === "simulation/reset") {
      if (user.role !== "ADMIN") return json({ detail: "Administrator permission required" }, 403);
      return json(resetSimulation());
    }
    if (path === "vehicles/location") return json({ ...DEMO_META, accepted: true, mode: "SIMULATION", message: "Location accepted only in this in-memory demo service." });
    if (path === "hubs/recommend") return json(recommendHubs(input));
    if (path === "copilot/query") { if (!String(input.query || "").trim()) return json({ detail: "query is required" }, 422); return json(copilotQuery(String(input.query))); }
    return json({ detail: `Unknown POST endpoint /api/${path}` }, 404);
  } catch (error) { return json({ detail: error instanceof Error ? error.message : "Invalid request" }, path === "auth/login" ? 401 : 422); }
}

export async function PATCH(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const path = (await params).path.join("/");
  const user = getUserFromSession(request.cookies.get(sessionCookieName())?.value);
  if (!user) return json({ detail: "Authentication required" }, 401);
  try {
    if (path.startsWith("alerts/") && path.endsWith("/acknowledge")) {
      if (!operationalRoles.has(user.role)) return json({ detail: "Operational role required" }, 403);
      return json(acknowledgeAlert(path.split("/")[1]));
    }
    if (path.startsWith("deliveries/") && path.endsWith("/status")) {
      if (!operationalRoles.has(user.role)) return json({ detail: "Operational role required" }, 403);
      return json({ ...DEMO_META, mode: "SIMULATION", delivery: updateDelivery(path.split("/")[1], await body(request)) });
    }
    return json({ detail: `Unknown PATCH endpoint /api/${path}` }, 404);
  } catch (error) {
    return json({ detail: error instanceof Error ? error.message : "Invalid request" }, 422);
  }
}

export async function DELETE(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const path = (await params).path.join("/");
  if (path !== "auth/logout") return json({ detail: `Unknown DELETE endpoint /api/${path}` }, 404);
  const response = json({ ok: true });
  response.cookies.set(sessionCookieName(), "", { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 0, path: "/" });
  return response;
}
